#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    nomad-blog-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^nomad-blog\.ddev\.site$`)
      
      service: "nomad-blog-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "nomad-blog-redirectHttps"
    nomad-blog-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^nomad-blog\.ddev\.site$`)
      
      service: "nomad-blog-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "nomad-blog-redirectHttps"
    
    
    
    nomad-blog-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^nomad-blog\.ddev\.site$`)
      
      service: "nomad-blog-web-80"
      ruleSyntax: v3
      
      tls: true
      
    nomad-blog-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^nomad-blog\.ddev\.site$`)
      
      service: "nomad-blog-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    nomad-blog-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    nomad-blog-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-nomad-blog-web:80
        
    nomad-blog-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-nomad-blog-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/nomad-blog.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/nomad-blog.key